# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     (cd pr-checks; pip install ruamel.yaml@0.17.31 && python3 sync.py)
# to regenerate this file.

name: PR Check - Extract directly to toolcache
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}
jobs:
  extract-direct-to-toolcache:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            version: linked
          - os: ubuntu-latest
            version: linked
    name: Extract directly to toolcache
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python on macOS
        uses: actions/setup-python@v5
        if: runner.os == 'macOS' && matrix.version == 'stable-v2.14.6'
        with:
          python-version: '3.11'
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Remove CodeQL from toolcache
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const codeqlPath = path.join(process.env['RUNNER_TOOL_CACHE'], 'CodeQL');
            fs.rmdirSync(codeqlPath, { recursive: true });
      - id: init
        uses: ./../action/init
        with:
          languages: javascript
          tools: ${{ steps.prepare-test.outputs.tools-url }}
      - uses: ./../action/analyze
        with:
          output: ${{ runner.temp }}/results
          upload-database: false
      - name: Install @actions/tool-cache
        run: npm install @actions/tool-cache
      - name: Check CodeQL is installed within the toolcache
        uses: actions/github-script@v7
        with:
          script: |
            const toolcache = require('@actions/tool-cache');
            const allCodeqlVersions = toolcache.findAllVersions('CodeQL');
            console.log(`Found CodeQL versions: ${allCodeqlVersions}`);
            if (allCodeqlVersions.length === 0) {
              throw new Error('CodeQL not found in toolcache');
            }
            if (allCodeqlVersions.length > 1) {
              throw new Error('Multiple CodeQL versions found in toolcache');
            }
            console.log(`CodeQL version: ${allCodeqlVersions[0]}`);
    env:
      CODEQL_ACTION_EXTRACT_TOOLCACHE: true
      CODEQL_ACTION_ZSTD_BUNDLE: true
      CODEQL_ACTION_TEST_MODE: true
